all:test.o add.o sub.o mul.o div.o
	gcc test.o add.o sub.o mul.o div.o
	
test.o:test.c
	gcc -c test.c
add.o:add.c
	gcc -c add.c
sub.o:sub.c
	gcc -c sub.c
mul.o:mul.c
	gcc -c mul.c
div.o:div.c
	gcc -c div.c
